sudo: required
services: 
  - docker

before_install:
  - docker build -t luuizpaulo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luuizpaulo/docker-react yarn run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-919123374228"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
